### ISSUE TITLE
License status of this project

### ISSUE THREAD

**Issue by james7132** [noblewhale/NATPunchthroughClient#4]
I would like to use this within an open source Unity project; however, this project has no license: @noblewhale thus reserves all rights to the project. I understand there is a non-free Unity Asset Store package for this, which is unusable within such an open source project.

Can the status of this project's licensing please be clarified via a LICENSE file or within the README?

**Comment by AnsonKindred** [comment]
Done. Use with caution, there have been bugs reported and I don't maintain this any more.
